import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import QueryProvider from "@/QueryProvider/QueryProvider"; 
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Task",
  description: "Generated by next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >

        <div>
          <NavBar></NavBar>
        </div>
        
        <div className="container my-20 mx-auto px-4 md:px-9  min-h-[calc(100vh-380px)]">
          <QueryProvider>
            <Toaster></Toaster>
              {children}
            
          </QueryProvider>
        </div>
         
      </body>
    </html>
  );
}
